Gongkademy/Gongkademy_Service_Front

- package-lock.json
- package.json
- src/components/common/editor/ToastUIEditor.jsx
- src/pages/Community/CommunityPage.jsx
- src/pages/Community/NavBar.jsx
- src/pages/CourseDetail/CourseDetailPage.jsx
- src/pages/Home/HomePage.jsx
- src/styles/editor.css
- resolve #15 
- ToastUIEditor 연결
- toolbarItems설정
> [Feat] toast UI 에디터 연결

- src/pages/CommunityBoard/Card/QnaCard.jsx
- resolve #25 
- QnA페이지에서 viibleIcon 수정
> Refactor: QnA페이지에서 viibleIcon 수정

- src/components/common/searchbar/SearchBar.jsx
- src/components/common/searchbar/Searchbar.style.js
- src/components/common/searchbar/Select.jsx
- resolve #35 
- Select의 너비를 props로 받아서 설정할 수 있
> Refactor: Select너비 props설정으로 변경

- src/apis/apiConstants.js
- src/apis/community/QnaApi.js
- src/apis/community/ReviewApi.js
- src/apis/community/concernApi.js
- src/apis/community/noticeApi.js
- resolve #39 
- src > apis > community에 고민, 공지사항, 질문, 댓글 관련 API정리
> FEAT: community api 추가

- src/components/common/select/MeetballSelect.jsx
- src/components/common/select/MeetballSelect.style.js
- src/pages/CommunityDetail/CommunityDetail.jsx
- src/pages/CommunityUpdate/CommunityUpdatePage.jsx
- src/router/AppRouter.jsx
- src/router/Constants.js
- resolve #46 
- 미트볼 아이콘 클릭 시 수정 및 삭제 버튼 활성화
- 수정페이지로 라우터 연결
> FEAT: 상세페이지에서 수정페이지 이동 + 미트볼클릭시 버튼활성화

- src/apis/axiosInstance.js
- src/apis/community/QnaApi.js
- src/apis/community/concernApi.js
- src/apis/community/noticeApi.js
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/stores/Community/ConcernStore.js
- src/stores/Community/NoticeStore.js
- src/stores/Community/QnaStore.js
- src/stores/Community/ReviewStore.js
- resolve #48 
- src > stores폴더 생성해서 Community관련 store들 생성
- 질문, 고민 리스트 가져오는 api수정 -> keword를 받아서 keyword에 따라 리스트 반환(검색)
- CommunityBoardPage에서 기존에 useState를 use(Qna or Concern)Store로 변경
- 공지사항도 마찬가지
- 500에러 발생..
> Feat: 커뮤니티 페이지 api연결 + 수정

- src/apis/community/QnaApi.js
- src/apis/community/concernApi.js
- resolve #52 
- 질문, 고민 리스트 가져올 때 pageNo, criteria파라미터 추가
> Refactor: 질문,고민 리스트 api파라미터 추가

- src/components/community/Card/CommunityCard.jsx
- src/components/community/Card/NoticeCard.jsx
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/pages/CommunityDetail/CommunityDetail.jsx
- resolve #57 
- 기존에 임의로 작성되었던 useState들을 store를 사용하여 변경
- 데이터 형식에 맞게 각 게시글들의 속성명 변경
> Refactor: 커뮤니티상세보기 & 리스트아이템(카드) 상태관리 수정(store사용) 및 변수명 변경

- src/apis/apiConstants.js
- src/components/community/Card/CommunityCard.jsx
- src/components/community/Card/NoticeCard.jsx
- resolve #60
- 기존에 requestmapping에 있던 community가 api적용이 되지 않아 404에러가 발생했음
- api에 community추가해서 404에러 해결
> Refactor: 커뮤니티 api수정(community추가)

- src/components/common/pagination/Pagination.jsx
- src/pages/Service/Community/CommunityPage.jsx
- resolve #67
- Pagination.jsx에서 Pagination.style경로 수정
- CommunityPage.jsx에서 Pagination.jsx경로 수정
> REFACTOR: pagination import코드 수정

- src/apis/community/QnaApi.js
- src/apis/community/concernApi.js
- src/components/community/Regist/RegistCourse.jsx
- src/components/community/Regist/RegistNav.jsx
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
- src/stores/Community/ConcernStore.js
- src/stores/Community/QnaStore.js
- resolve #62
- concern, question store의 게시글 작성 함수 코드 수정
- 고민 또는 질문에 따라 게시물 등록 완료
- 이후 조회 시 공지사항으로 조회됨.(해결해야할 것)
> feat 게시물 등록 post요청

- src/apis/apiConstants.js
- src/apis/axiosInstance.js
- src/apis/course/adminCourseApi.js
- resolve #71 
- 관리자용 API instance 구현
- End Point 작성
- 호출 메소드 구현
> Feat: 강의,강좌 관리자 기능 API 설정

- src/apis/apiConstants.js
- src/apis/course/adminCourseApi.js
- src/components/common/imageUpload/ImageUpload.jsx
- src/components/common/imageUpload/ImageUpload.style.js
- src/pages/Admin/Lecture/AdminLecturePage.jsx
- src/pages/Admin/LectureRegist/AdminLectureRegistPage.jsx
- src/router/AppRouter.jsx
- resolve #69 
- 
-  메인페이지에서 강좌등록페이지로 이동
- 이미지 업로드 하는 컴포넌트 구현
- API연결
> Feat: 관리자 강의 등록 페이지 디자인+API 작업

- src/apis/apiConstants.js
- src/apis/course/courseApi.js
- src/apis/course/courseCommentApi.js
- src/apis/course/courseReviewApi.js
- src/apis/course/playerApi.js
- resolve #77 
- API End Point 작성
- 호출 함성 작성
> Feat: 서비스 강의,강좌에 필요한 API 호출함수 작성

- src/apis/community/QnaApi.js
- src/apis/community/ReviewApi.js
- src/apis/community/concernApi.js
- src/apis/community/noticeApi.js
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/stores/Community/ConcernStore.js
- src/stores/Community/NoticeStore.js
- resolve #79 
- 커뮤니티 관련 api비동기 설정
- 커뮤니티 관련 store 코드 수정
> FIX: 커뮤니티 리스트 조회 에러 수정

- src/apis/apiConstants.js
- src/apis/course/adminCourseApi.js
- src/apis/course/courseApi.js
- src/components/admin/navbar/AdminCourseNavbar.jsx
- src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
- src/hooks/useForm.jsx
- src/pages/Admin/CourseOrder/AdminCourseOrderPage.jsx
- resolve #76 
- 강의 목차 조회
- 강의 목차 추가
- 강의 목차 수정
- 강의 목차 삭제
> Feat: 관리자 강의 목차 페이지 구현 (디자인+api)

- jsconfig.json
- src/components/common/rating/Rating.jsx
- src/components/common/review/Review.jsx
- src/components/common/searchbar/SearchBar.jsx
- src/components/common/select/Select.jsx
- src/components/community/Card/CommunityCard.jsx
- src/components/community/Card/NoticeCard.jsx
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/components/course/CourseCard.jsx
- src/components/courseDetail/courseSummary/CourseSummary.jsx
- src/components/lecture/lectureFooter/LectureFooter.jsx
- src/pages/Admin/CourseOrder/AdminCourseOrderPage.jsx
- src/pages/Service/Community/CommunityPage.jsx
- src/pages/Service/CommunityDetail/CommunityDetail.jsx
- src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
- src/pages/Service/Courses/CoursesPage.jsx
- src/stores/Community/ConcernStore.js
- src/stores/Community/NoticeStore.js
- src/stores/Community/QnaStore.js
- vite.config.js
- resolve #86 
- path alias 설정이후 프론트 서버 안뜨는 문제
> Fix: path alias 설정이후 프론트 서버 안뜨는 문제

- package-lock.json
- package.json
- src/apis/apiConstants.js
- src/apis/course/courseApi.js
- src/apis/course/playerApi.js
- src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
- src/components/courseDetail/courseSummary/CourseSummary.jsx
- src/components/lecture/lectureFooter/LectureFooter.jsx
- src/components/lecture/lectureHeader/LectureHeader.jsx
- src/components/lecture/lecturePlayer/LecturePlayer.jsx
- src/pages/Service/Lecture/LecturePage.jsx
- src/pages/Service/Lecture/constants.js
- src/stores/course/lectureStore.js
- resolve #89 
- 저장된 수강기간부터 자동재생
- 강의 수강구간 저장
- 다음강의, 이전강의 재생
- 강좌 수강기능
> Feat: 강의플레이어 재생기능 구현

- src/apis/apiConstants.js
- src/apis/axiosInstance.js
- src/components/header/Header.jsx
- src/pages/Service/GoogleRedirect/GoogleRedirectPage.jsx
- resolve #102 
- 리프레시토큰 만료시 API 요청하면 자동 로그인 시도 구현
- 로그아웃시 스토리지 값 삭제
- 권한이 필요한 응답에서 자동 로그인 구현
> 102 feat 로그인 토큰 만료시 헤더 변경 구현

- src/pages/Service/MemberDelete/MemberDeletePage.jsx
- src/pages/Service/MyCommunity/MyCommunityPage.jsx
- src/pages/Service/MyCourse/MyCoursePage.jsx
- src/pages/Service/MyInfoOut/MyInfoOutPage.jsx
- src/pages/Service/MyInfoUpdate/MyInfoUpdatePage.jsx
- src/pages/Service/MyNotificationSetting/MyNotificationSettingPage.jsx
- src/pages/Service/MyPage/MyPage.jsx
- src/router/AppRouter.jsx
- src/router/Constants.js
- resolve #107 
- 마이페이지 라우터 구현
> FEAT: 마이페이지 라우터 구현

- src/apis/apiConstants.js
- src/apis/axiosInstance.js
- src/apis/members/membersApi.js
- src/pages/Service/Home/HomePage.jsx
- src/router/AppRouter.jsx
- src/router/PrivaterRouter.jsx
- resolve #109 
- 권한이 맞지않을때 Home으로 이동(버그 있어서 주석처리)
> Feat: protected router 구현

- src/apis/community/QnaApi.js
- src/apis/community/concernApi.js
- src/apis/community/noticeApi.js
- src/components/community/Card/CommunityCard.jsx
- src/components/community/Card/NoticeCard.jsx
- src/components/community/communityBoard/CommunityBoardPage.jsx
- src/pages/Service/Community/CommunityPage.jsx
- src/pages/Service/CommunityDetail/CommunityDetail.jsx
- src/stores/Community/ConcernStore.js
- src/stores/Community/NoticeStore.js
- src/stores/Community/QnaStore.js
- resolve #112 
- 비로그인 관련 api추가
- 리스트 및 상세보기 비로그인  로그인 구분
- 비로그인일 때 좋아요, 스크랩, 글 등록 클릭시 로그인페이지로 이동
> REFACTOR:커뮤니티 비로그인 로그인 구분 수정

- package-lock.json
- src/apis/apiConstants.js
- src/apis/common/imageApi.js
- src/apis/course/adminCourseApi.js
- src/components/admin/course/CourseIntroEditor.jsx
- src/components/common/editor/QuillEditor.style.js
- src/components/common/textarea/TextArea.jsx
- src/components/common/textbox/TextBox.jsx
- src/components/common/textbox/Textbox.style.js
- src/components/courseDetail/courseIntroduction/CourseIntroduction.jsx
- src/hooks/useForm.jsx
- src/pages/Admin/Course/AdminCoursePage.jsx
- src/pages/Admin/CourseIntro/AdminCourseIntroPage.jsx
- src/queries/useCourseDetailQuery.js
- resolve #106 
- 관리자페이지에서 글작성, 수정기능 구현
- 서비스페이지에서 글 조회 기능 구현
> Feat: 강의 소개페이지 구현

- src/apis/course/adminCourseApi.js
- src/apis/course/courseApi.js
- src/components/admin/course/CourseEditor.jsx
- src/components/common/textbox/TextBox.jsx
- src/components/common/textbox/Textbox.style.js
- src/index.jsx
- src/pages/Admin/CourseIntro/AdminCourseIntroPage.jsx
- src/pages/Admin/CourseNotice/AdminCourseNoticePage.jsx
- src/queries/queryClient.js
- src/queries/useCourseDetailQuery.js
- resolve #122 
- 관리자페이지 강좌 공지사항 CRUD 기능 구현
> Feat: 강의 공지사항 기능 구현(관리자)
